apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
spec:
  containers:
  - name: myapp
    image: myapp-image
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: my-config1
          key: environment
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: my-config1
          key: log_level

