apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-07-04T06:03:14Z"
  generation: 1
  labels:
    app: my-nginx-deployment
  name: my-nginx-deployment
  namespace: devops-lab
  resourceVersion: "13450"
  uid: 33ff4498-5f0a-476b-9faa-62bcb27c5e7e
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-nginx-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx-deployment
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
