apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-demo
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx-service-demo
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-lb-svc

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-demo
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      name: http-lb-svc
  clusterIP: 10.96.0.121
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
